name: codingInventory
author: codingPotato
main: com.codingPotato.codingInventory.CodingInventory
version: 0.0.1
api-version: 1.14
website: 
dev-url: 
commands:
    stackitem:
        aliases: [si]
        description: Allows you to change any item's max stack amount.
        usage: