name: codingInventory
author: codingPotato
main: com.egirlsnation.codingInventory.CodingInventory
version: 0.0.1
api-version: 1.14
website: https://github.com/EgirlsNationDev/codingInventory
dev-url: https://github.com/EgirlsNationDev/codingInventory